:: validate
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\JARAUA_2017_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\ABUF_2013_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\AUAT_2012_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\BIO_2015_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\BLOW_2013_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\CP_2015_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\FLON_2013_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\QDR_2001_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\TLO_2015_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\TNS_2015_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\UNIN_2012_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\ALINE_2016_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\FERN_2016_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\IZA_2014_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\MVEMB_2015_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\POLY_2016_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\TREES_2016_2015_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880"

:: insert
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\JARAUA_2017_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880,--insert=true"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\ABUF_2013_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880,--insert=true"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\AUAT_2012_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880,--insert=true"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\BIO_2015_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880,--insert=true"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\BLOW_2013_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880,--insert=true"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\CP_2015_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880,--insert=true"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\FLON_2013_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880,--insert=true"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\QDR_2001_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880,--insert=true"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\TLO_2015_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880,--insert=true"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\TNS_2015_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880,--insert=true"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\UNIN_2012_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880,--insert=true"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\ALINE_2016_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880,--insert=true"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\FERN_2016_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880,--insert=true"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\IZA_2014_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880,--insert=true"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\MVEMB_2015_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880,--insert=true"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\POLY_2016_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880,--insert=true"
::mvn spring-boot:run -Drun.arguments="--spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\TREES_2016_2015_RESUMO.csv,--owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv,--shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880,--insert=true"

:: Final

:: validate
::java -jar plotdata-1.0-SNAPSHOT.jar --spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\JARAUA_2017_RESUMO.csv --owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv --shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880

:: insert
::java -jar plotdata-1.0-SNAPSHOT.jar --spreadsheet=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\data\JARAUA_2017_RESUMO.csv --owner=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\responsaveis_parcelas.csv --shapefiles=C:\Users\EBA\Documents\data\RESUMO_DADOS_PARCEIROS\shp\epsg_5880 --insert=true